// JsFromRoutes CacheKey 32748b6fdd2a68467157911f212e4146
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/recipes/:recipe_id/comments'),
  create: definePathHelper('post', '/recipes/:recipe_id/comments'),
  new: definePathHelper('get', '/recipes/:recipe_id/comments/new'),
  edit: definePathHelper('get', '/recipes/:recipe_id/comments/:id/edit'),
  get: definePathHelper('get', '/recipes/:recipe_id/comments/:id'),
  update: definePathHelper('patch', '/recipes/:recipe_id/comments/:id'),
  destroy: definePathHelper('delete', '/recipes/:recipe_id/comments/:id'),
}
