// JsFromRoutes CacheKey fe76610db3c391a112558b933bf87924
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: definePathHelper('get', '/new'),
  create: definePathHelper('post', '/new'),
  edit: definePathHelper('get', '/edit'),
  update: definePathHelper('patch', '/edit'),
}
