// JsFromRoutes CacheKey b0c1f7ea51915671aea37a007286332c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as usersSessions } from '~/api/Users/SessionsApi'
export { default as usersRegistrations } from '~/api/Users/RegistrationsApi'
export { default as recipes } from '~/api/RecipesApi'
export { default as inertiaExample } from '~/api/InertiaExampleApi'
export { default as pages } from '~/api/PagesApi'
export { default as users } from '~/api/UsersApi'
export { default as favorites } from '~/api/FavoritesApi'
