// JsFromRoutes CacheKey 59a045b933dbb474391f6c2be55a6ca6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as usersSessions } from "~/api/Users/SessionsApi";
export { default as usersRegistrations } from "~/api/Users/RegistrationsApi";
export { default as recipes } from "~/api/RecipesApi";
export { default as inertiaExample } from "~/api/InertiaExampleApi";
export { default as pages } from "~/api/PagesApi";
export { default as users } from "~/api/UsersApi";
