// JsFromRoutes CacheKey beccaca730c31769821b799fba31f1eb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: definePathHelper('post', '/favorites'),
  destroy: definePathHelper('delete', '/favorites/:id'),
}
