// JsFromRoutes CacheKey 68681f966ab025384d5fdd1045a926fe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/inertia-example'),
}
