// JsFromRoutes CacheKey 352913cfc5f326ad98183d405436d4ea
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  home: definePathHelper('get', '/pages/home'),
}
