// JsFromRoutes CacheKey f6f813cc57cb5b55cc7f40cbd1320170
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/'),
  create: definePathHelper('post', '/recipes'),
  new: definePathHelper('get', '/recipes/new'),
  edit: definePathHelper('get', '/recipes/:id/edit'),
  get: definePathHelper('get', '/recipes/:id'),
  update: definePathHelper('patch', '/recipes/:id'),
  destroy: definePathHelper('delete', '/recipes/:id'),
  favorites: definePathHelper('get', '/recipe/favorites'),
}
