// JsFromRoutes CacheKey 52394ce41cbcb1c2455329948ebaf623
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  get: definePathHelper('get', '/users/:id'),
}
